#!/bin/sh -e
# Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# This file is sourced from main.sh to update distro-specific defaults.
# It must set at least ARCH and MIRROR if not already specified.

if [ -z "$ARCH" ]; then
    ARCH="`uname -m | sed -e 's i.86 i386 ;s x86_64 amd64 ;s arm.* armhf ;'`"
fi

if [ -z "$MIRROR" ]; then
    if [ "$ARCH" = 'x86_64' -o "$ARCH" = 'i586' ]; then
        MIRROR='http://ftp.aarnet.edu.au/pub/mageia/'
    else
        MIRROR='http://packages.rtp-net.org/mageia/1/armv5tl/'

        fi
fi

