#!/bin/sh -e
# Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# This is a distro-specific continuation of the prepare.sh script.


# Add media to urpmi
# eg /usr/sbin/urpmi.addmedia --distrib http://packages.rtp-net.org/mageia/1/armv5tl
/usr/sbin/urpmi.addmedia --distrib $MIRROR/../../../

# ensure we are in /
cd /

# Reinstall all packages with urpmi
for rpm in *.rpm; do /usr/sbin/urpmi "$rpm" --allow-force --ignoresize; done

# Remove all manually downloaded rpm packages
rm /*.rpm

# ln -sf /proc/mounts /etc/mtab
# ????????????????????
# mount command still doesn't work
# Remount / as read write?
