#!/bin/sh -e
# Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

exec /usr/bin/Xvnc -nevershared -dontdisconnect -localhost -once \
                   -geometry 1024x768 -depth 16 "$@"
